package com.lizheblogs.domainsearch.bean.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WHOIS".
 */
public class Whois {

    private Long id;
    private String domain_name;
    private String registrar;
    private String creation_date;
    private String expiration_date;
    private String updated_date;
    private String registrant_name;
    private String registrant_country;
    private String registrant_phone;
    private String admin_name;
    private String admin_phone;
    private String tech_name;
    private String tech_phone;
    private String original_info;

    public Whois() {
    }

    public Whois(String domain_name) {
        this.domain_name = domain_name;
    }

    public Whois(Long id, String domain_name, String registrar, String creation_date, String expiration_date, String updated_date, String registrant_name, String registrant_country, String registrant_phone, String admin_name, String admin_phone, String tech_name, String tech_phone, String original_info) {
        this.id = id;
        this.domain_name = domain_name;
        this.registrar = registrar;
        this.creation_date = creation_date;
        this.expiration_date = expiration_date;
        this.updated_date = updated_date;
        this.registrant_name = registrant_name;
        this.registrant_country = registrant_country;
        this.registrant_phone = registrant_phone;
        this.admin_name = admin_name;
        this.admin_phone = admin_phone;
        this.tech_name = tech_name;
        this.tech_phone = tech_phone;
        this.original_info = original_info;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDomain_name() {
        return domain_name;
    }

    public void setDomain_name(String domain_name) {
        this.domain_name = domain_name;
    }

    public String getRegistrar() {
        return registrar;
    }

    public void setRegistrar(String registrar) {
        this.registrar = registrar;
    }

    public String getCreation_date() {
        return creation_date;
    }

    public void setCreation_date(String creation_date) {
        this.creation_date = creation_date;
    }

    public String getExpiration_date() {
        return expiration_date;
    }

    public void setExpiration_date(String expiration_date) {
        this.expiration_date = expiration_date;
    }

    public String getUpdated_date() {
        return updated_date;
    }

    public void setUpdated_date(String updated_date) {
        this.updated_date = updated_date;
    }

    public String getRegistrant_name() {
        return registrant_name;
    }

    public void setRegistrant_name(String registrant_name) {
        this.registrant_name = registrant_name;
    }

    public String getRegistrant_country() {
        return registrant_country;
    }

    public void setRegistrant_country(String registrant_country) {
        this.registrant_country = registrant_country;
    }

    public String getRegistrant_phone() {
        return registrant_phone;
    }

    public void setRegistrant_phone(String registrant_phone) {
        this.registrant_phone = registrant_phone;
    }

    public String getAdmin_name() {
        return admin_name;
    }

    public void setAdmin_name(String admin_name) {
        this.admin_name = admin_name;
    }

    public String getAdmin_phone() {
        return admin_phone;
    }

    public void setAdmin_phone(String admin_phone) {
        this.admin_phone = admin_phone;
    }

    public String getTech_name() {
        return tech_name;
    }

    public void setTech_name(String tech_name) {
        this.tech_name = tech_name;
    }

    public String getTech_phone() {
        return tech_phone;
    }

    public void setTech_phone(String tech_phone) {
        this.tech_phone = tech_phone;
    }

    public String getOriginal_info() {
        return original_info;
    }

    public void setOriginal_info(String original_info) {
        this.original_info = original_info;
    }

}
