package com.lizheblogs.domainsearch.data.local;

import android.database.sqlite.SQLiteDatabase;

import com.lizheblogs.domainsearch.bean.db.Domain;
import com.lizheblogs.domainsearch.bean.db.Whois;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig domainDaoConfig;
    private final DaoConfig whoisDaoConfig;

    private final DomainDao domainDao;
    private final WhoisDao whoisDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        domainDaoConfig = daoConfigMap.get(DomainDao.class).clone();
        domainDaoConfig.initIdentityScope(type);

        whoisDaoConfig = daoConfigMap.get(WhoisDao.class).clone();
        whoisDaoConfig.initIdentityScope(type);

        domainDao = new DomainDao(domainDaoConfig, this);
        whoisDao = new WhoisDao(whoisDaoConfig, this);

        registerDao(Domain.class, domainDao);
        registerDao(Whois.class, whoisDao);
    }
    
    public void clear() {
        domainDaoConfig.getIdentityScope().clear();
        whoisDaoConfig.getIdentityScope().clear();
    }

    public DomainDao getDomainDao() {
        return domainDao;
    }

    public WhoisDao getWhoisDao() {
        return whoisDao;
    }

}
